### PR TITLE
Feat/add metadata to supportedOptions for passing additional info

### PR DESCRIPTION
**Pull request by mmohajer**
The purpose is to add an option to the list of `supportedOptions` in order to be able to pass any additional information regarding the string. This new options is called `metadata` and we can pass it as an object. For example, let's say we want to associate different tags to the strings. Using this new options we can have something like this:

`t("Translate me {{count}} times", {count: 100, metadata: {tags: ['tag1', 'tag2']}})`

Note that what we define for `metadata` is a custom object based on the information we want to pass and in the above example, we used tags.

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included

Screen Shot 2022-06-15 at 9 58 43 AM

#### Checklist (for documentation change)

- [x] only relevant documentation part is changed (make a diff before you submit the PR)
- [x] motivation/reason is provided

### CODE REVIEW

**Comment by mmohajer** [comment]
Hi @sitek94 @cheton! I noticed you were the recent contributor/reviewer and I was wondering if you guys could give me some info on how I can add reviewers for this PR and get some eyes on it. It seems I don't have access to add reviewers. Thanks!

**Comment by cheton** [comment]
Hi @mmohajer,

Sorry for that I don't quite understand your purpose of adding external options, because I cannot find the differences according to your new test case and was unable to find any relevant `i18next` docs related to the `collection` key.

Can you explain that in more detail and update the test cases to see how it works? Thanks.

**Comment by cheton** [comment]
Thanks for your explanation. I'm just thinking about the key name. How about using `metadata` instead of `externalOptions`?

**Review by cheton — APPROVED** [review]

**Comment by cheton** [comment]
Published v3.2.0

https://www.npmjs.com/package/i18next-scanner?activeTab=versions

**Comment by delphiactual** [comment]
@mmohajer do you have example usage of how to use this? I understand adding the `metadata` property into my codebase but I do not understand how I can use the metadata I provide to for example update a dynamic context list.

**Pull request merged**
