### PR TITLE
Introduce an option to specify the line endings.

### PR DESCRIPTION
**Pull request by messerm**
Maybe you prefer a less invasive approach than https://github.com/i18next/i18next-scanner/pull/67

### CODE REVIEW

**Comment by cheton** [comment]
This PR can be closed as it's been resolved in [v2.3.0](https://github.com/i18next/i18next-scanner/releases/tag/v2.3.0)

```js
{
  resource: {
    // Normalize line endings to '\r\n', '\r', '\n', or 'auto' for the current operating system.
    // Defaults to '\n'.
    // Aliases: 'CRLF', 'CR', 'LF', 'crlf', 'cr', 'lf'
    lineEnding: '\n'
  }
}
```

**Comment by messerm** [comment]
Nice.. thanks for the changes. I now have to find a way to add BOM.

**Comment by messerm** [comment]
Regarding the BOM, is this also something you would consider to add here as an option?

**Comment by cheton** [comment]
You should save resource files as UTF-8 without BOM, or it will break a JSON text. May I know for what purpose you may want to add BOM as an option?

**Comment by messerm** [comment]
https://stackoverflow.com/questions/1045663/why-would-i-use-a-unicode-signature-byte-order-mark-bom
UTF files and especially localized files should probably always have bom to avoid issues around UTF-8, 16 and little/big indian. In the worst case the app will load them wrong and display wrong characters.

**Comment by messerm** [comment]
https://stackoverflow.com/questions/4990095/json-specification-and-usage-of-bom-charset-encoding
never mind.. maybe our problems in the past have been fixed now.

**Pull request closed without merging**
